version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    #    container_name:
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
#      - POSTGRES_HOST_AUTH_METHOD=trust

  server:
    build: /server
    #    image:
    #    container_name:
    ports:
      - "9090:9090"
    depends_on:
      - db
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  gateway:
    build: /gateway
    #    image:
    #    container_name:
    ports:
      - "8080:8080"
    depends_on:
      - server
#    environment:
#      - SHAREIT_SERVER_URL=http://server:9090
