drop table if exists  booking, comments, item, item_request, users ;

create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(127) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id)
--  ,  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
create unique index if not exists USER_ID_UINDEX on USERS (id);
create unique index if not exists USER_EMAIL_UINDEX on USERS (email);

create table if not exists item_request(
id bigint generated by default as identity not null,
description varchar(255),
requestor_id bigint not null REFERENCES users(id),
created timestamp without time zone not null,
constraint pk_itenRequest primary key (id)
);

create table if not exists item (
id bigint Generated by default as identity not null,
name varchar(255)  not null,
description varchar(255) not null,
available boolean not null,
owner_id BIGINT not null REFERENCES  users(id),
request_id BIGINT REFERENCES item_request(id),
constraint pk_item primary key (id)
);
create unique index if not exists ITEM_ID_UINDEX on USERS (id);

create table if not exists booking (
id bigint Generated by default as identity not null,
start_date timestamp WITHOUT TIME ZONE not null,
end_date timestamp WITHOUT TIME ZONE not null,
item_id bigint not null REFERENCES item(id),
booker_id bigint not null references users(id),
status varchar(255) not null,
constraint pk_booking primary key (id)
);

create table if not exists comments (
id bigint generated by default as identity not null,
text varchar not null,
item_id bigint not null REFERENCES item(id),
author_id bigint not null REFERENCES users(id),
created timestamp WITHOUT TIME ZONE not null,
constraint pk_comments primary key (id)
);

























