CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(127) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
create table if not exists item (
id bigint Generated by default as identity not null,
name varchar(255)  not null,
description varchar(255) not null,
available boolean not null,
owner BIGINT not null,
request BIGINT,
constraint pk_item primary key (id)
);